version: 2
project_name: ghacron

before:
  hooks:
    - go mod tidy

builds:
  - id: ghacron
    main: ./main.go
    binary: ghacron
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: ghacron
    builds:
      - ghacron
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: korosuke613
    name: ghacron
  draft: false
  prerelease: auto
